### ISSUE TITLE
AWS: LoadBalancer services do not work and are in state Pending

### ISSUE THREAD

**Issue by arne-rusek** [mayadata-io/mayastor-terraform-playground#7]
That is because we use `kubeadm` to create the cluster instead of AWS EKS kubernetes distribution which doesn't support AWS ELB.

You can access the services by using external IP service like this (replace IP `ExternalIPs` by private IP of your master node). You need to allow external traffic to master to port 9000 resp. to port of your service.
```
apiVersion: v1
kind: Service
metadata:
        name: minio
spec:
  externalIPs:
          - 10.0.2.67
  ports:
          - name: http
            port: 9000
            protocol: TCP
            targetPort: 9000
  selector:
          app: minio
  type: ClusterIP
```
